
name: beta-build-schedule
on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:  # allows manual runs

jobs:
  commits:
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
          name: checkout
          with:
            clean: false
            fetch-depth: 0
        - name: changes
          id: changes
          run: |
              
              echo "::set-output name=changes::$(git log $(git describe --tags --abbrev=0)..HEAD --no-merges --oneline)"
              git log $(git describe --tags --abbrev=0)..HEAD --no-merges --oneline
        - name: test
          run: |
              echo "num: ${{steps.changes.outputs.changes}}"
              
        - name: Repository Dispatch
          if: steps.commits.outputs.changes != '0'
          uses: peter-evans/repository-dispatch@v1
          with:
            token: ${{ secrets.GH_TOKEN }}
            repository: pkegg/351ELEC
            event-type: upstream-commit
