name: update-pkegg-main
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/**'
      - 'README.md'
      - 'Dockerfile'
      - '.dockerignore'
    branches:
      - 351elec-fetcher
jobs:
  build:
    runs-on: ubuntu
    steps:
      - uses: hmarr/debug-action@v2
        name: debug
      - uses: actions/checkout@v2
        name: checkout
        with:
          clean: false
      
      - name: Update main
        run: |
            set -e
            UPSTREAM=351ELEC-upstream
            git remote rm ${UPSTREAM}
            git remote add ${UPSTREAM} https://github.com/351ELEC/351ELEC
            git fetch ${UPSTREAM}
            git branch -D main
            git branch main ${UPSTREAM}/main
            git push --force main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


