
name: release-beta
on:
  schedule:
    - cron:  '*/5 * * * *'
  workflow_dispatch:  # allows manual runs

    
jobs:
  commits:
      runs-on: ubuntu-20.04
      steps:
        - uses: hmarr/debug-action@v2
          name: debug
        - uses: actions/checkout@v2
          name: checkout
          with:
            clean: false
            fetch-depth: 0
        - name: changes
          id: changes
          run: |
              echo "::set-output name=changes::$(git log $(git describe --tags --abbrev=0)..HEAD --no-merges --oneline | wc -l)"
              echo "::set-output name=release_notes::$(git log $(git describe --tags --abbrev=0)..HEAD --no-merges --oneline)"
        - name: Get date for artifacts
          id: date
          run: echo "::set-output name=date::$(date +'%Y%m%d_%H%M')"
        - name: Repository Dispatch
          if: steps.changes.outputs.changes != '0'
          uses: peter-evans/repository-dispatch@v1
          with:
            token: ${{ secrets.TRIGGER_BUILD_TOKEN }}
            repository: ${{ github.event.repository.full_name }}
            event-type: release-beta
            client-payload: |
               {
                 "release_tag" : "beta-${{steps.date.outputs.date}}",
                 "release_notes" : "${{steps.changes.outputs.release_notes}}"
               }
            
